name: daily-scan
on:
  push:
    branches:
      - main
jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install trufflehog
        run: |
          pip install truffleHog
          
      - name: Create Directory and File
        run: |
          mkdir -p output
        
      - name: Run trufflehog
        run: |
          trufflehog git --repo $(pwd) > output/issue.txt || true
          cat output/issue.txt | sed 's/\x1b\[[0-9;]*m//g' | grep -E 'Reason|Date|Hash|Filepath|Branch|Commit' | sed 's/^[[:space:]]*//' | awk '{
              if ($1 == "Branch:") {
                  branch = $2; 
                  gsub("origin/", "", branch);  # Remove "origin/" prefix for file naming
                  
                  # Check if branch is not empty
                  if (branch != "") {
                      file = "output/" branch ".txt";  # Create a filename based on the branch name
                      print "";  # Start new entry
                  }
              }
              if (file) {
                  print > file;  # Redirect to the appropriate file only if file is valid
              }
          }'
        #run: |
        #  trufflehog git --repo $(pwd) > output/issue.txt || true
        #  cat output/issue.txt | sed 's/\x1b\[[0-9;]*m//g' |
        #    grep -E 'Reason|Date|Hash|Filepath|Branch|Commit' |
        #    sed 's/^[[:space:]]*//' | awk 'ORS=NR%6?"\n":"\n\n"' > output/filtered_issue.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: output/  #filtered_issue.txt
