name: Daily Entire Repo Secret Scan

on:
  schedule:
    - cron: '0 0 * * *'
    
jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install trufflehog
        run: |
          pip install truffleHog
          
      - name: Create Output Directory
        run: |
          mkdir -p output
        
      - name: Run trufflehog
        run: |
          trufflehog git --repo $(pwd) > output/issue.txt || true
          cat output/issue.txt | sed 's/\x1b\[[0-9;]*m//g' | grep -E 'Reason|Date|Hash|Filepath|Branch|Commit' | sed 's/^[[:space:]]*//' | awk '{
              if ($1 == "Branch:") {
                  if (file) { print "" > file; }
                  branch = $2; 
                  gsub("origin/", "", branch); 
                  if (branch != "") {
                      file = "output/" branch ".txt"; 
                  }
              }
              if (file) {
                  print > file; 
              }
          }
          END {
              if (file) { print "" > file; }
          }'
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: output/
