on:
  pull_request
jobs:
  lox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Run TruffleHog OSS and save logs
        id: trufflehog
        run: |
          # Run TruffleHog and redirect output to a log file
          trufflehog --path ./ --base ${{ github.event.repository.default_branch }} --head HEAD --debug --only-verified > trufflehog_logs.txt || true
          
      - name: Upload TruffleHog logs as artifact
        uses: actions/upload-artifact@v3
        with:
          name: trufflehog-logs
          path: trufflehog_logs.txt
